/* Datasets for the Japanese learning app.
   Each kana entry: { kana, romaji }
   Each kanji entry: { kanji, reading, romaji, meaning }
   dictionary: lowercased English -> Japanese map used by the Translate view. */

const hiragana = [
  // Gojūon (base 46)
  { kana: "あ", romaji: "a" }, { kana: "い", romaji: "i" }, { kana: "う", romaji: "u" }, { kana: "え", romaji: "e" }, { kana: "お", romaji: "o" },
  { kana: "か", romaji: "ka" }, { kana: "き", romaji: "ki" }, { kana: "く", romaji: "ku" }, { kana: "け", romaji: "ke" }, { kana: "こ", romaji: "ko" },
  { kana: "さ", romaji: "sa" }, { kana: "し", romaji: "shi" }, { kana: "す", romaji: "su" }, { kana: "せ", romaji: "se" }, { kana: "そ", romaji: "so" },
  { kana: "た", romaji: "ta" }, { kana: "ち", romaji: "chi" }, { kana: "つ", romaji: "tsu" }, { kana: "て", romaji: "te" }, { kana: "と", romaji: "to" },
  { kana: "な", romaji: "na" }, { kana: "に", romaji: "ni" }, { kana: "ぬ", romaji: "nu" }, { kana: "ね", romaji: "ne" }, { kana: "の", romaji: "no" },
  { kana: "は", romaji: "ha" }, { kana: "ひ", romaji: "hi" }, { kana: "ふ", romaji: "fu" }, { kana: "へ", romaji: "he" }, { kana: "ほ", romaji: "ho" },
  { kana: "ま", romaji: "ma" }, { kana: "み", romaji: "mi" }, { kana: "む", romaji: "mu" }, { kana: "め", romaji: "me" }, { kana: "も", romaji: "mo" },
  { kana: "や", romaji: "ya" }, { kana: "ゆ", romaji: "yu" }, { kana: "よ", romaji: "yo" },
  { kana: "ら", romaji: "ra" }, { kana: "り", romaji: "ri" }, { kana: "る", romaji: "ru" }, { kana: "れ", romaji: "re" }, { kana: "ろ", romaji: "ro" },
  { kana: "わ", romaji: "wa" }, { kana: "を", romaji: "wo" }, { kana: "ん", romaji: "n" },
  // Dakuten / handakuten
  { kana: "が", romaji: "ga" }, { kana: "ぎ", romaji: "gi" }, { kana: "ぐ", romaji: "gu" }, { kana: "げ", romaji: "ge" }, { kana: "ご", romaji: "go" },
  { kana: "ざ", romaji: "za" }, { kana: "じ", romaji: "ji" }, { kana: "ず", romaji: "zu" }, { kana: "ぜ", romaji: "ze" }, { kana: "ぞ", romaji: "zo" },
  { kana: "だ", romaji: "da" }, { kana: "ぢ", romaji: "ji" }, { kana: "づ", romaji: "zu" }, { kana: "で", romaji: "de" }, { kana: "ど", romaji: "do" },
  { kana: "ば", romaji: "ba" }, { kana: "び", romaji: "bi" }, { kana: "ぶ", romaji: "bu" }, { kana: "べ", romaji: "be" }, { kana: "ぼ", romaji: "bo" },
  { kana: "ぱ", romaji: "pa" }, { kana: "ぴ", romaji: "pi" }, { kana: "ぷ", romaji: "pu" }, { kana: "ぺ", romaji: "pe" }, { kana: "ぽ", romaji: "po" },
  // Yōon (combinations)
  { kana: "きゃ", romaji: "kya" }, { kana: "きゅ", romaji: "kyu" }, { kana: "きょ", romaji: "kyo" },
  { kana: "しゃ", romaji: "sha" }, { kana: "しゅ", romaji: "shu" }, { kana: "しょ", romaji: "sho" },
  { kana: "ちゃ", romaji: "cha" }, { kana: "ちゅ", romaji: "chu" }, { kana: "ちょ", romaji: "cho" },
  { kana: "にゃ", romaji: "nya" }, { kana: "にゅ", romaji: "nyu" }, { kana: "にょ", romaji: "nyo" },
  { kana: "ひゃ", romaji: "hya" }, { kana: "ひゅ", romaji: "hyu" }, { kana: "ひょ", romaji: "hyo" },
  { kana: "みゃ", romaji: "mya" }, { kana: "みゅ", romaji: "myu" }, { kana: "みょ", romaji: "myo" },
  { kana: "りゃ", romaji: "rya" }, { kana: "りゅ", romaji: "ryu" }, { kana: "りょ", romaji: "ryo" },
  { kana: "ぎゃ", romaji: "gya" }, { kana: "ぎゅ", romaji: "gyu" }, { kana: "ぎょ", romaji: "gyo" },
  { kana: "じゃ", romaji: "ja" }, { kana: "じゅ", romaji: "ju" }, { kana: "じょ", romaji: "jo" },
  { kana: "びゃ", romaji: "bya" }, { kana: "びゅ", romaji: "byu" }, { kana: "びょ", romaji: "byo" },
  { kana: "ぴゃ", romaji: "pya" }, { kana: "ぴゅ", romaji: "pyu" }, { kana: "ぴょ", romaji: "pyo" }
];

const katakana = [
  // Gojūon (base 46)
  { kana: "ア", romaji: "a" }, { kana: "イ", romaji: "i" }, { kana: "ウ", romaji: "u" }, { kana: "エ", romaji: "e" }, { kana: "オ", romaji: "o" },
  { kana: "カ", romaji: "ka" }, { kana: "キ", romaji: "ki" }, { kana: "ク", romaji: "ku" }, { kana: "ケ", romaji: "ke" }, { kana: "コ", romaji: "ko" },
  { kana: "サ", romaji: "sa" }, { kana: "シ", romaji: "shi" }, { kana: "ス", romaji: "su" }, { kana: "セ", romaji: "se" }, { kana: "ソ", romaji: "so" },
  { kana: "タ", romaji: "ta" }, { kana: "チ", romaji: "chi" }, { kana: "ツ", romaji: "tsu" }, { kana: "テ", romaji: "te" }, { kana: "ト", romaji: "to" },
  { kana: "ナ", romaji: "na" }, { kana: "ニ", romaji: "ni" }, { kana: "ヌ", romaji: "nu" }, { kana: "ネ", romaji: "ne" }, { kana: "ノ", romaji: "no" },
  { kana: "ハ", romaji: "ha" }, { kana: "ヒ", romaji: "hi" }, { kana: "フ", romaji: "fu" }, { kana: "ヘ", romaji: "he" }, { kana: "ホ", romaji: "ho" },
  { kana: "マ", romaji: "ma" }, { kana: "ミ", romaji: "mi" }, { kana: "ム", romaji: "mu" }, { kana: "メ", romaji: "me" }, { kana: "モ", romaji: "mo" },
  { kana: "ヤ", romaji: "ya" }, { kana: "ユ", romaji: "yu" }, { kana: "ヨ", romaji: "yo" },
  { kana: "ラ", romaji: "ra" }, { kana: "リ", romaji: "ri" }, { kana: "ル", romaji: "ru" }, { kana: "レ", romaji: "re" }, { kana: "ロ", romaji: "ro" },
  { kana: "ワ", romaji: "wa" }, { kana: "ヲ", romaji: "wo" }, { kana: "ン", romaji: "n" },
  // Dakuten / handakuten
  { kana: "ガ", romaji: "ga" }, { kana: "ギ", romaji: "gi" }, { kana: "グ", romaji: "gu" }, { kana: "ゲ", romaji: "ge" }, { kana: "ゴ", romaji: "go" },
  { kana: "ザ", romaji: "za" }, { kana: "ジ", romaji: "ji" }, { kana: "ズ", romaji: "zu" }, { kana: "ゼ", romaji: "ze" }, { kana: "ゾ", romaji: "zo" },
  { kana: "ダ", romaji: "da" }, { kana: "ヂ", romaji: "ji" }, { kana: "ヅ", romaji: "zu" }, { kana: "デ", romaji: "de" }, { kana: "ド", romaji: "do" },
  { kana: "バ", romaji: "ba" }, { kana: "ビ", romaji: "bi" }, { kana: "ブ", romaji: "bu" }, { kana: "ベ", romaji: "be" }, { kana: "ボ", romaji: "bo" },
  { kana: "パ", romaji: "pa" }, { kana: "ピ", romaji: "pi" }, { kana: "プ", romaji: "pu" }, { kana: "ペ", romaji: "pe" }, { kana: "ポ", romaji: "po" },
  // Yōon (combinations)
  { kana: "キャ", romaji: "kya" }, { kana: "キュ", romaji: "kyu" }, { kana: "キョ", romaji: "kyo" },
  { kana: "シャ", romaji: "sha" }, { kana: "シュ", romaji: "shu" }, { kana: "ショ", romaji: "sho" },
  { kana: "チャ", romaji: "cha" }, { kana: "チュ", romaji: "chu" }, { kana: "チョ", romaji: "cho" },
  { kana: "ニャ", romaji: "nya" }, { kana: "ニュ", romaji: "nyu" }, { kana: "ニョ", romaji: "nyo" },
  { kana: "ヒャ", romaji: "hya" }, { kana: "ヒュ", romaji: "hyu" }, { kana: "ヒョ", romaji: "hyo" },
  { kana: "ミャ", romaji: "mya" }, { kana: "ミュ", romaji: "myu" }, { kana: "ミョ", romaji: "myo" },
  { kana: "リャ", romaji: "rya" }, { kana: "リュ", romaji: "ryu" }, { kana: "リョ", romaji: "ryo" },
  { kana: "ギャ", romaji: "gya" }, { kana: "ギュ", romaji: "gyu" }, { kana: "ギョ", romaji: "gyo" },
  { kana: "ジャ", romaji: "ja" }, { kana: "ジュ", romaji: "ju" }, { kana: "ジョ", romaji: "jo" },
  { kana: "ビャ", romaji: "bya" }, { kana: "ビュ", romaji: "byu" }, { kana: "ビョ", romaji: "byo" },
  { kana: "ピャ", romaji: "pya" }, { kana: "ピュ", romaji: "pyu" }, { kana: "ピョ", romaji: "pyo" }
];

const kanji = [
  // Numbers
  { kanji: "一", reading: "いち / ichi", romaji: "ichi", meaning: "one" },
  { kanji: "二", reading: "に / ni", romaji: "ni", meaning: "two" },
  { kanji: "三", reading: "さん / san", romaji: "san", meaning: "three" },
  { kanji: "四", reading: "し・よん / shi, yon", romaji: "yon", meaning: "four" },
  { kanji: "五", reading: "ご / go", romaji: "go", meaning: "five" },
  { kanji: "六", reading: "ろく / roku", romaji: "roku", meaning: "six" },
  { kanji: "七", reading: "しち・なな / shichi, nana", romaji: "nana", meaning: "seven" },
  { kanji: "八", reading: "はち / hachi", romaji: "hachi", meaning: "eight" },
  { kanji: "九", reading: "きゅう / kyuu", romaji: "kyuu", meaning: "nine" },
  { kanji: "十", reading: "じゅう / juu", romaji: "juu", meaning: "ten" },
  { kanji: "百", reading: "ひゃく / hyaku", romaji: "hyaku", meaning: "hundred" },
  { kanji: "千", reading: "せん / sen", romaji: "sen", meaning: "thousand" },
  { kanji: "万", reading: "まん / man", romaji: "man", meaning: "ten thousand" },
  // Days of the week / time
  { kanji: "日", reading: "にち・ひ / nichi, hi", romaji: "nichi", meaning: "day / sun" },
  { kanji: "月", reading: "げつ・つき / getsu, tsuki", romaji: "getsu", meaning: "month / moon" },
  { kanji: "火", reading: "か・ひ / ka, hi", romaji: "ka", meaning: "fire" },
  { kanji: "水", reading: "すい・みず / sui, mizu", romaji: "sui", meaning: "water" },
  { kanji: "木", reading: "もく・き / moku, ki", romaji: "moku", meaning: "tree / wood" },
  { kanji: "金", reading: "きん・かね / kin, kane", romaji: "kin", meaning: "gold / money" },
  { kanji: "土", reading: "ど・つち / do, tsuchi", romaji: "do", meaning: "earth / soil" },
  { kanji: "年", reading: "ねん・とし / nen, toshi", romaji: "nen", meaning: "year" },
  { kanji: "時", reading: "じ・とき / ji, toki", romaji: "ji", meaning: "time / hour" },
  { kanji: "今", reading: "いま・こん / ima, kon", romaji: "ima", meaning: "now" },
  { kanji: "週", reading: "しゅう / shuu", romaji: "shuu", meaning: "week" },
  // People / common nouns
  { kanji: "人", reading: "ひと・じん / hito, jin", romaji: "hito", meaning: "person" },
  { kanji: "男", reading: "おとこ・だん / otoko, dan", romaji: "otoko", meaning: "man" },
  { kanji: "女", reading: "おんな・じょ / onna, jo", romaji: "onna", meaning: "woman" },
  { kanji: "子", reading: "こ・し / ko, shi", romaji: "ko", meaning: "child" },
  { kanji: "母", reading: "はは / haha", romaji: "haha", meaning: "mother" },
  { kanji: "父", reading: "ちち / chichi", romaji: "chichi", meaning: "father" },
  { kanji: "友", reading: "とも・ゆう / tomo, yuu", romaji: "tomo", meaning: "friend" },
  { kanji: "名", reading: "な・めい / na, mei", romaji: "na", meaning: "name" },
  { kanji: "国", reading: "くに・こく / kuni, koku", romaji: "kuni", meaning: "country" },
  { kanji: "学", reading: "がく / gaku", romaji: "gaku", meaning: "study / learning" },
  { kanji: "校", reading: "こう / kou", romaji: "kou", meaning: "school" },
  { kanji: "先", reading: "せん・さき / sen, saki", romaji: "sen", meaning: "previous / ahead" },
  { kanji: "生", reading: "せい・い / sei, i", romaji: "sei", meaning: "life / birth" },
  { kanji: "本", reading: "ほん / hon", romaji: "hon", meaning: "book / origin" },
  { kanji: "車", reading: "くるま・しゃ / kuruma, sha", romaji: "kuruma", meaning: "car" },
  { kanji: "店", reading: "みせ・てん / mise, ten", romaji: "mise", meaning: "shop / store" },
  { kanji: "駅", reading: "えき / eki", romaji: "eki", meaning: "station" },
  { kanji: "山", reading: "やま・さん / yama, san", romaji: "yama", meaning: "mountain" },
  { kanji: "川", reading: "かわ / kawa", romaji: "kawa", meaning: "river" },
  { kanji: "田", reading: "た・でん / ta, den", romaji: "ta", meaning: "rice field" },
  { kanji: "雨", reading: "あめ・う / ame, u", romaji: "ame", meaning: "rain" },
  { kanji: "気", reading: "き / ki", romaji: "ki", meaning: "spirit / energy" },
  { kanji: "電", reading: "でん / den", romaji: "den", meaning: "electricity" },
  { kanji: "語", reading: "ご / go", romaji: "go", meaning: "language / word" },
  { kanji: "話", reading: "はなし・わ / hanashi, wa", romaji: "hanashi", meaning: "talk / story" },
  // Common verbs / adjectives
  { kanji: "行", reading: "い(く)・こう / iku, kou", romaji: "iku", meaning: "to go" },
  { kanji: "来", reading: "く(る)・らい / kuru, rai", romaji: "kuru", meaning: "to come" },
  { kanji: "見", reading: "み(る)・けん / miru, ken", romaji: "miru", meaning: "to see" },
  { kanji: "聞", reading: "き(く)・ぶん / kiku, bun", romaji: "kiku", meaning: "to hear / ask" },
  { kanji: "食", reading: "た(べる)・しょく / taberu, shoku", romaji: "taberu", meaning: "to eat" },
  { kanji: "飲", reading: "の(む)・いん / nomu, in", romaji: "nomu", meaning: "to drink" },
  { kanji: "読", reading: "よ(む)・どく / yomu, doku", romaji: "yomu", meaning: "to read" },
  { kanji: "書", reading: "か(く)・しょ / kaku, sho", romaji: "kaku", meaning: "to write" },
  { kanji: "話", reading: "はな(す) / hanasu", romaji: "hanasu", meaning: "to speak" },
  { kanji: "買", reading: "か(う)・ばい / kau, bai", romaji: "kau", meaning: "to buy" },
  { kanji: "大", reading: "おお(きい)・だい / ookii, dai", romaji: "ookii", meaning: "big" },
  { kanji: "小", reading: "ちい(さい)・しょう / chiisai, shou", romaji: "chiisai", meaning: "small" },
  { kanji: "中", reading: "なか・ちゅう / naka, chuu", romaji: "naka", meaning: "middle / inside" },
  { kanji: "上", reading: "うえ・じょう / ue, jou", romaji: "ue", meaning: "up / above" },
  { kanji: "下", reading: "した・か / shita, ka", romaji: "shita", meaning: "down / below" },
  { kanji: "左", reading: "ひだり・さ / hidari, sa", romaji: "hidari", meaning: "left" },
  { kanji: "右", reading: "みぎ・う / migi, u", romaji: "migi", meaning: "right" },
  { kanji: "新", reading: "あたら(しい)・しん / atarashii, shin", romaji: "atarashii", meaning: "new" },
  { kanji: "古", reading: "ふる(い)・こ / furui, ko", romaji: "furui", meaning: "old" },
  { kanji: "高", reading: "たか(い)・こう / takai, kou", romaji: "takai", meaning: "high / expensive" },
  { kanji: "安", reading: "やす(い)・あん / yasui, an", romaji: "yasui", meaning: "cheap / safe" },
  { kanji: "白", reading: "しろ・はく / shiro, haku", romaji: "shiro", meaning: "white" },
  { kanji: "黒", reading: "くろ・こく / kuro, koku", romaji: "kuro", meaning: "black" },
  { kanji: "赤", reading: "あか・せき / aka, seki", romaji: "aka", meaning: "red" },
  { kanji: "青", reading: "あお・せい / ao, sei", romaji: "ao", meaning: "blue" }
];

/* Curated English -> Japanese dictionary (keys lowercased).
   Used for instant offline lookups before falling back to the API. */
const dictionary = {
  "hello": "こんにちは",
  "hello how are you": "こんにちは、お元気ですか",
  "hi": "やあ",
  "hi how are you": "やあ、元気ですか",
  "good morning": "おはようございます",
  "good evening": "こんばんは",
  "good night": "おやすみなさい",
  "goodbye": "さようなら",
  "bye": "じゃあね",
  "thank you": "ありがとう",
  "thanks": "ありがとう",
  "thank you very much": "ありがとうございます",
  "you're welcome": "どういたしまして",
  "please": "お願いします",
  "excuse me": "すみません",
  "sorry": "ごめんなさい",
  "yes": "はい",
  "no": "いいえ",
  "maybe": "たぶん",
  "ok": "オーケー",
  "okay": "オーケー",
  "nice to meet you": "はじめまして",
  "how are you": "お元気ですか",
  "how are you doing": "お元気ですか",
  "i am fine": "元気です",
  "i'm fine": "元気です",
  "i am good": "元気です",
  "i'm good": "元気です",
  "what is this": "これは何ですか",
  "what is that": "あれは何ですか",
  "where are you from": "どこから来ましたか",
  "i am from": "私は〜から来ました",
  "can you help me": "助けてもらえますか",
  "i don't know": "知りません",
  "i know": "知っています",
  "let me know": "教えてください",
  "thank you so much": "本当にありがとうございます",
  "that's okay": "大丈夫です",
  "no problem": "問題ありません",
  "of course": "もちろん",
  "see you later": "また後で",
  "see you tomorrow": "また明日",
  "welcome": "ようこそ",
  "congratulations": "おめでとう",
  "cheers": "乾杯",
  "good luck": "頑張って",
  "i love you": "愛してる",
  "i like it": "好きです",
  "i don't understand": "わかりません",
  "i understand": "わかります",
  "do you speak english": "英語を話せますか",
  "what is your name": "お名前は何ですか",
  "my name is": "私の名前は",
  "where is the bathroom": "トイレはどこですか",
  "how much is it": "いくらですか",
  "i'm hungry": "お腹がすいた",
  "i'm thirsty": "喉が渇いた",
  "delicious": "おいしい",
  "help": "助けて",
  "wait": "待って",
  "let's go": "行きましょう",
  "i": "私",
  "you": "あなた",
  "he": "彼",
  "she": "彼女",
  "we": "私たち",
  "they": "彼ら",
  "name": "名前",
  "friend": "友達",
  "family": "家族",
  "mother": "母",
  "father": "父",
  "child": "子供",
  "man": "男",
  "woman": "女",
  "person": "人",
  "teacher": "先生",
  "student": "学生",
  "doctor": "医者",
  "water": "水",
  "fire": "火",
  "food": "食べ物",
  "rice": "ご飯",
  "tea": "お茶",
  "coffee": "コーヒー",
  "beer": "ビール",
  "milk": "牛乳",
  "bread": "パン",
  "fish": "魚",
  "meat": "肉",
  "vegetable": "野菜",
  "fruit": "果物",
  "apple": "りんご",
  "egg": "卵",
  "book": "本",
  "school": "学校",
  "house": "家",
  "home": "家",
  "car": "車",
  "train": "電車",
  "station": "駅",
  "city": "町",
  "country": "国",
  "money": "お金",
  "shop": "店",
  "store": "店",
  "phone": "電話",
  "computer": "コンピューター",
  "dog": "犬",
  "cat": "猫",
  "bird": "鳥",
  "mountain": "山",
  "river": "川",
  "sea": "海",
  "sky": "空",
  "sun": "太陽",
  "moon": "月",
  "star": "星",
  "rain": "雨",
  "snow": "雪",
  "wind": "風",
  "flower": "花",
  "tree": "木",
  "morning": "朝",
  "afternoon": "昼",
  "evening": "夕方",
  "night": "夜",
  "today": "今日",
  "tomorrow": "明日",
  "yesterday": "昨日",
  "now": "今",
  "day": "日",
  "week": "週",
  "month": "月",
  "year": "年",
  "time": "時間",
  "monday": "月曜日",
  "tuesday": "火曜日",
  "wednesday": "水曜日",
  "thursday": "木曜日",
  "friday": "金曜日",
  "saturday": "土曜日",
  "sunday": "日曜日",
  "red": "赤",
  "blue": "青",
  "green": "緑",
  "yellow": "黄色",
  "white": "白",
  "black": "黒",
  "big": "大きい",
  "small": "小さい",
  "new": "新しい",
  "old": "古い",
  "hot": "暑い",
  "cold": "寒い",
  "good": "良い",
  "bad": "悪い",
  "happy": "幸せ",
  "sad": "悲しい",
  "beautiful": "美しい",
  "cute": "かわいい",
  "expensive": "高い",
  "cheap": "安い",
  "fast": "速い",
  "slow": "遅い",
  "one": "一",
  "two": "二",
  "three": "三",
  "four": "四",
  "five": "五",
  "six": "六",
  "seven": "七",
  "eight": "八",
  "nine": "九",
  "ten": "十",
  "hundred": "百",
  "thousand": "千",
  "to go": "行く",
  "to come": "来る",
  "to eat": "食べる",
  "to drink": "飲む",
  "to see": "見る",
  "to hear": "聞く",
  "to read": "読む",
  "to write": "書く",
  "to speak": "話す",
  "to buy": "買う",
  "to do": "する",
  "to sleep": "寝る",
  "to study": "勉強する",
  "to work": "働く",
  "love": "愛",
  "japan": "日本",
  "japanese": "日本語",
  "english": "英語",
  "language": "言葉"
};
